/*
 * This code was generated by a tool.
 */

const url = "/spa-api/";
const jsonCT = new Headers();
jsonCT.append('Content-Type', 'application/json');

function jsonRequest(method, args=[], kwargs={}) {
    return new Promise((resolve, reject) => {
        fetch(url, {
            method: 'POST',
            headers: jsonCT,
            credentials: 'include',
            body: JSON.stringify({method,args,kwargs,"version":2})
        }).then(response => {
            if (response.status === 200) {
                response.json().then(res => {
                    if (!res.success) {
                        console.error(`[API] ${res.error}: ${res.error_message}`);
                        const error = new Error(res.error_message || res.error);
                        error.code = res.error;
                        reject(error);
                    } else {
                        resolve(res.result);
                    }
                });
            } else {
                const error = new Error(`HTTP ${response.status}: ${response.statusText}`);
                error.status = response.status;
                reject(error);
            }
        }).catch(error => reject(error));
    });
}


export function getMethods() { return jsonRequest('getMethods'); }
export function getDetails() { return jsonRequest('getDetails'); }
export function hasCapability(capability) { return jsonRequest('hasCapability', [capability]); }
export function get_user(username) { return jsonRequest('get_user', [username]); }
export function logoff() { return jsonRequest('logoff'); }
export function logoff_all() { return jsonRequest('logoff_all'); }
export function login(user, otp) { return jsonRequest('login', [user, otp]); }
export function send_otp(username) { return jsonRequest('send_otp', [username]); }
export function register_user(username, role) { return jsonRequest('register_user', [username, role]); }
export function set_user_role(username, role) { return jsonRequest('set_user_role', [username, role]); }
export function list_roles() { return jsonRequest('list_roles'); }
export function get_all_users() { return jsonRequest('get_all_users'); }
export function check_user() { return jsonRequest('check_user'); }
export function get_actions_tree(hidden=true) { return jsonRequest('get_actions_tree', [hidden]); }
export function call_action(section, action, hidden=true) { return jsonRequest('call_action', [section, action, hidden]); }
export function call_action_by_name(section, action) { return jsonRequest('call_action_by_name', [section, action]); }
export function get_applications() { return jsonRequest('get_applications'); }
